// The value of dynamicParams control the behavior when a route that is not
// generated by generateStaticParams(). It is true by default.
// If the value is false, then routes that are not generated by
// generateStaticParams will return 404.
export const dynamicParams = false;

import { getProductById } from 'frontend-api/products';
import { notFound } from 'next/navigation';
import { Product } from 'types/product.type';

export async function generateStaticParams() {
  const res = await fetch('https://dummyjson.com/products/');

  const data: { products: Product[] } = await res.json();

  const products = data.products;

  // 100 versions of this page will be statically generated
  // using the `params` returned by `generateStaticParams`
  // - /product/1
  // - /product/2
  // - /product/3
  return products.map((product) => ({
    id: product.id.toString(),
  }));
}

export default async function Page({ params }: { params: { id: string } }) {
  const { id } = params;

  const product: Product = await getProductById(id);

  if (!product) {
    notFound();
  }

  return (
    <>
      <p>Product name is : {product.title}</p>
    </>
  );
}
